# Generated by Django 2.2 on 2023-07-17 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('background_task', '0003_auto_20200130_1326'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatedTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue', models.CharField(blank=True, db_index=True, max_length=190, null=True)),
                ('was_updated', models.BooleanField(default=True)),
            ],
        ),
    ]
