# Generated by Django 4.2.7 on 2024-01-11 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("background_task", "0003_auto_20200130_1326"),
    ]

    operations = [
        migrations.AlterField(
            model_name="completedtask",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
